_base: &_base
  test_size: 0.1
  trainer:
    batch_size: 128
    epochs: 200
    lam_smooth: 0.0
    learning_rate: 0.001
    weight_decay: 0.0


online_mlp:
  base:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: relu
      dropout_rates: [0.3, 0.3, 0.3]
      hidden_dims: [64, 64, 32]
      use_batchnorm: true
  base_sum:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: relu
      dropout_rates: [0.3, 0.3, 0.3]
      hidden_dims: [64, 64, 32]
      use_batchnorm: true
      reduce: sum


online_lstm:
  base:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: gelu
      dropout_rates: [0.0, 0.0]
      hidden_dims: [64, 64]
      lstm_dropout: 0.3
      lstm_hidden_dim: 256
      lstm_layers: 2
      use_batchnorm: true

  bo:
    test_size: 0.1
    trainer: {batch_size: 128, epochs: 200, lam_smooth: 0.0, learning_rate: 0.0007015412676067785, weight_decay: 0.007466210341627973}
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      act_name: relu
      dropout_rates: [0.3, 0.5]
      hidden_dims: [64, 128]
      lstm_dropout: 0.4447447004082546
      lstm_hidden_dim: 64
      lstm_layers: 3
      use_batchnorm: true
online_attention:
  base:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: gelu
      attn_dim: 128
      attn_heads: 4
      attn_dropout: 0.1
      ffn_dim: 256
      ffn_dropout: 0.1
      hidden_dims: [64, 32]
      dropout_rates: [0.2, 0.2]
      use_batchnorm: true
      use_ffn: true

  # bo:
  #   test_size: 0.1
  #   trainer: {batch_size: 128, epochs: 200, lam_smooth: 0.0, learning_rate: 0.0005526803165459961, weight_decay: 0.0028914898585685835}
  #   features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D]
  #   args:
  #     act_name: relu
  #     attn_dim: 256
  #     attn_heads: 2
  #     attn_dropout: 0.013345994417725202
  #     ffn_dim: 1024
  #     ffn_dropout: 0.26176968124930355
  #     hidden_dims: [32]
  #     dropout_rates: [0.5]
  #     use_batchnorm: true
  #     use_ffn: true

  bo:
    test_size: 0.1
    trainer: {batch_size: 128, epochs: 200, lam_smooth: 0.0, learning_rate: 0.0006345598580577934, weight_decay: 0.0022235838234001626}
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      act_name: relu
      attn_dim: 256
      attn_heads: 2
      attn_dropout: 0.05459011351289604
      ffn_dim: 1024
      ffn_dropout: 0.22655542515741103
      hidden_dims: [128, 32, 128]
      dropout_rates: [0.0, 0.4, 0.1]
      use_batchnorm: true
      use_ffn: true
offline_lstm:
  base:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: gelu
      bidirectional: true
      dropout_rates: [0.0, 0.0]
      hidden_dims: [64, 64]
      lstm_dropout: 0.3
      lstm_hidden_dim: 256
      lstm_layers: 2
      use_batchnorm: true


offline_regression:
  base:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      C: 1.0
      max_iter: 1000
      solver: lbfgs
      random_state: 0
      basis:
        IMU_VerAccelVal: [sqrt_mean, max]
        Bounce_rate_6D: [sqrt_mean, max]
        Pitch_rate_6D: [sqrt_mean, max]
        IMU_LongAccelVal: [sqrt_mean, max]

online_regression:
  base:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      C: 100.0
      solver: lbfgs
      max_iter: 1000
      random_state: 0
      basis:
        IMU_VerAccelVal: [abs, quad]
        Bounce_rate_6D: [abs, quad]
        Pitch_rate_6D: [abs, quad]
        IMU_LongAccelVal: [abs, quad]

  quad_exp:
    <<: *_base
    args:
      C: 0.06576916117983621
      form: quad_exp
      max_iter: 1000
      random_state: 0
      solver: lbfgs
      w3: [1.0, 1.0, 1.0, 1.0]
      w4: [0.0, 0.0, 0.0, 0.0]
  bo:
    test_size: 0.1
    trainer: {batch_size: 128, epochs: 200, lam_smooth: 0.0, learning_rate: 0.001, weight_decay: 0.0}
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      C: 0.11113159879347126
      solver: lbfgs
      max_iter: 1000
      random_state: 0
      basis:
        IMU_VerAccelVal: [abs, shifted_exp]
        Bounce_rate_6D: [cube, shifted_exp]
        Pitch_rate_6D: [abs, quad]
        IMU_LongAccelVal: [quad]
      w3: {IMU_VerAccelVal: 20.273254267274467, Bounce_rate_6D: 9.905230067883263}
      w4: {IMU_VerAccelVal: 0.43577550748761884, Bounce_rate_6D: 1.0141475472774526}
