_neural:
  test_size: 0.1
  trainer:
    batch_size: 128
    epochs: 200
    lam_smooth: 0.0
    learning_rate: 0.0005
    weight_decay: 0.0

_regression: &_regression
  test_size: 0.1

_base: &_base
  test_size: 0.1
  trainer:
    batch_size: 128
    epochs: 200
    lam_smooth: 0.0
    learning_rate: 0.001
    weight_decay: 0.0


online_mlp:
  base:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: relu
      dropout_rates: [0.3, 0.3, 0.3]
      hidden_dims: [64, 64, 32]
      use_batchnorm: true
  base_sum:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: relu
      dropout_rates: [0.3, 0.3, 0.3]
      hidden_dims: [64, 64, 32]
      use_batchnorm: true
      reduce: sum


online_lstm:
  base:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: gelu
      dropout_rates: [0.0, 0.0]
      hidden_dims: [64, 64]
      lstm_dropout: 0.3
      lstm_hidden_dim: 256
      lstm_layers: 2
      use_batchnorm: true


  bo:
    test_size: 0.1
    trainer: {batch_size: 128, epochs: 200, lam_smooth: 0.0, learning_rate: 0.000993508917847292, weight_decay: 0.0005120175510907348}
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      act_name: gelu
      dropout_rates: [0.0, 0.4, 0.1]
      hidden_dims: [128, 128, 64]
      lstm_dropout: 0.0027157481252189633
      lstm_hidden_dim: 256
      lstm_layers: 2
      use_batchnorm: true
      input_dim: 4
    active_feature_indices: [0, 1, 2, 3]
online_attention:
  base:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: gelu
      attn_dim: 128
      attn_heads: 4
      attn_dropout: 0.1
      ffn_dim: 256
      ffn_dropout: 0.1
      hidden_dims: [64, 32]
      dropout_rates: [0.2, 0.2]
      use_batchnorm: true
      use_ffn: true

  bo:
    test_size: 0.1
    trainer: {batch_size: 128, epochs: 200, lam_smooth: 0.0, learning_rate: 0.0006345598580577934, weight_decay: 0.0022235838234001626}
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      act_name: relu
      attn_dim: 256
      attn_heads: 2
      attn_dropout: 0.05459011351289604
      ffn_dim: 1024
      ffn_dropout: 0.22655542515741103
      hidden_dims: [128, 32, 128]
      dropout_rates: [0.0, 0.4, 0.1]
      use_batchnorm: true
      use_ffn: true


offline_lstm:
  base:
    <<: *_base
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: gelu
      bidirectional: true
      dropout_rates: [0.0, 0.0]
      hidden_dims: [64, 64]
      lstm_dropout: 0.3
      lstm_hidden_dim: 256
      lstm_layers: 2
      use_batchnorm: true


online_regression:
  base:
    <<: *_regression
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      C: 100.0
      solver: lbfgs
      max_iter: 1000
      random_state: 0
      basis:
        IMU_VerAccelVal: [abs, quad]
        Bounce_rate_6D: [abs, quad]
        Pitch_rate_6D: [abs, quad]
        IMU_LongAccelVal: [abs, quad]

  quad_exp:
    <<: *_regression
    args:
      C: 0.06576916117983621
      form: quad_exp
      max_iter: 1000
      random_state: 0
      solver: lbfgs
      w3: [1.0, 1.0, 1.0, 1.0]
      w4: [0.0, 0.0, 0.0, 0.0]
  bo:
    test_size: 0.1
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      C: 67.72340912743816
      solver: lbfgs
      max_iter: 1000
      random_state: 0
      basis:
        IMU_VerAccelVal: [abs, cube]
        Bounce_rate_6D: [abs, shifted_exp]
        Pitch_rate_6D: [cube, shifted_exp]
        IMU_LongAccelVal: [abs, quad, cube]
      w3: {Bounce_rate_6D: 7.626444715428141, Pitch_rate_6D: 0.5820692759067339}
      w4: {Bounce_rate_6D: 0.17932918028173445, Pitch_rate_6D: 39.24260818989988}
    active_feature_indices: [0, 1, 2, 3]

offline_regression:
  base:
    <<: *_regression
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      C: 1.0
      max_iter: 1000
      solver: lbfgs
      random_state: 0
      basis:
        IMU_VerAccelVal: [sqrt_mean, max]
        Bounce_rate_6D: [sqrt_mean, max]
        Pitch_rate_6D: [sqrt_mean, max]
        IMU_LongAccelVal: [sqrt_mean, max]
  bo:
    test_size: 0.1
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      C: 5.272412272294474
      max_iter: 1000
      solver: lbfgs
      random_state: 0
      basis:
        IMU_VerAccelVal: [abs_mean, sqrt_mean]
        Bounce_rate_6D: [std, abs_mean]
        Pitch_rate_6D: [mean, max, abs_mean, sqrt_mean]
        IMU_LongAccelVal: [mean, max, abs_mean]
    active_feature_indices: [0, 1, 2, 3]
