_neural: &_neural
  test_size: 0.1
  trainer:
    batch_size: 128
    epochs: 200
    lam_smooth: 0.0
    learning_rate: 0.0005
    weight_decay: 0.0

_regression: &_regression
  test_size: 0.1


online_mlp:
  base:
    <<: *_neural
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: relu
      dropout_rates: [0.3, 0.3, 0.3]
      hidden_dims: [64, 64, 32]
      use_batchnorm: true
  base_sum:
    <<: *_neural
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: relu
      dropout_rates: [0.3, 0.3, 0.3]
      hidden_dims: [64, 64, 32]
      use_batchnorm: true
      reduce: sum
online_lstm:
  base:
    <<: *_neural
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: gelu
      dropout_rates: [0.0, 0.0]
      hidden_dims: [64, 64]
      lstm_dropout: 0.3
      lstm_hidden_dim: 256
      lstm_layers: 2
      use_batchnorm: true

  bo:
    test_size: 0.1
    trainer: {batch_size: 128, epochs: 200, lam_smooth: 0.0, learning_rate: 0.0009331944459528507, weight_decay: 0.0003765141629751754}
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      act_name: tanh
      dropout_rates: [0.2, 0.1]
      hidden_dims: [128, 32]
      lstm_dropout: 0.4472275733990106
      lstm_hidden_dim: 256
      lstm_layers: 3
      use_batchnorm: true
      input_dim: 4
    active_feature_indices: [0, 1, 2, 3]
online_attention:
  base:
    <<: *_neural
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: gelu
      attn_dim: 128
      attn_heads: 4
      attn_dropout: 0.1
      ffn_dim: 256
      ffn_dropout: 0.1
      hidden_dims: [64, 32]
      dropout_rates: [0.2, 0.2]
      use_batchnorm: true
      use_ffn: true

  # bo:
  #   test_size: 0.1
  #   trainer: {batch_size: 128, epochs: 200, lam_smooth: 0.0, learning_rate: 0.0005526803165459961, weight_decay: 0.0028914898585685835}
  #   features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D]
  #   args:
  #     act_name: relu
  #     attn_dim: 256
  #     attn_heads: 2
  #     attn_dropout: 0.013345994417725202
  #     ffn_dim: 1024
  #     ffn_dropout: 0.26176968124930355
  #     hidden_dims: [32]
  #     dropout_rates: [0.5]
  #     use_batchnorm: true
  #     use_ffn: true

  bo:
    test_size: 0.1
    trainer: {batch_size: 128, epochs: 200, lam_smooth: 0.0, learning_rate: 0.0006345598580577934, weight_decay: 0.0022235838234001626}
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      act_name: relu
      attn_dim: 256
      attn_heads: 2
      attn_dropout: 0.05459011351289604
      ffn_dim: 1024
      ffn_dropout: 0.22655542515741103
      hidden_dims: [128, 32, 128]
      dropout_rates: [0.0, 0.4, 0.1]
      use_batchnorm: true
      use_ffn: true
offline_lstm:
  base:
    <<: *_neural
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      act_name: gelu
      bidirectional: true
      dropout_rates: [0.0, 0.0]
      hidden_dims: [64, 64]
      lstm_dropout: 0.3
      lstm_hidden_dim: 256
      lstm_layers: 2
      use_batchnorm: true


offline_regression:
  base:
    <<: *_regression
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      C: 1.0
      max_iter: 1000
      solver: lbfgs
      random_state: 0
      basis:
        IMU_VerAccelVal: [sqrt_mean, max]
        Bounce_rate_6D: [sqrt_mean, max]
        Pitch_rate_6D: [sqrt_mean, max]
        IMU_LongAccelVal: [sqrt_mean, max]
  bo:
    test_size: 0.1
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      C: 19.574394233501994
      max_iter: 1000
      solver: lbfgs
      random_state: 0
      basis:
        IMU_VerAccelVal: [min, abs_mean, sqrt_mean, rmse]
        Bounce_rate_6D: [std, max, abs_mean, rmse]
        Pitch_rate_6D: [min]
        IMU_LongAccelVal: [mean, max, abs_mean, sqrt_mean]
    active_feature_indices: [0, 1, 2, 3]

online_regression:
  base:
    <<: *_regression
    features:
    - IMU_VerAccelVal
    - Bounce_rate_6D
    - Pitch_rate_6D
    - IMU_LongAccelVal
    args:
      C: 100.0
      solver: lbfgs
      max_iter: 1000
      random_state: 0
      basis:
        IMU_VerAccelVal: [abs, quad]
        Bounce_rate_6D: [abs, quad]
        Pitch_rate_6D: [abs, quad]
        IMU_LongAccelVal: [abs, quad]

  quad_exp:
    <<: *_regression
    args:
      C: 0.06576916117983621
      form: quad_exp
      max_iter: 1000
      random_state: 0
      solver: lbfgs
      w3: [1.0, 1.0, 1.0, 1.0]
      w4: [0.0, 0.0, 0.0, 0.0]
  bo:
    test_size: 0.1
    features: [IMU_VerAccelVal, Bounce_rate_6D, Pitch_rate_6D, IMU_LongAccelVal]
    args:
      C: 99.2941224236526
      solver: lbfgs
      max_iter: 1000
      random_state: 0
      basis:
        IMU_VerAccelVal: [abs, quad, shifted_exp]
        Bounce_rate_6D: [shifted_exp]
        Pitch_rate_6D: [shifted_exp]
        IMU_LongAccelVal: [abs, quad, shifted_exp]
      w3: {IMU_VerAccelVal: 1.2205331046854342, Bounce_rate_6D: 8.808411577892894, Pitch_rate_6D: 0.44943334758365, IMU_LongAccelVal: 49.296860511400084}
      w4: {IMU_VerAccelVal: 44.895547863405696, Bounce_rate_6D: 36.81752652226854, Pitch_rate_6D: 47.52455020819025, IMU_LongAccelVal: 0.1355079147131126}
    active_feature_indices: [0, 1, 2, 3]
