_base: &_base
  test_size: 0.1
  trainer:
    batch_size: 128
    epochs: 200
    lam_smooth: 0.0
    learning_rate: 0.001
    weight_decay: 0.0

offline_lstm:
  base:
    <<: *_base
    test_size: 0.1
    features:
      - IMU_VerAccelVal
      - Bounce_rate_6D
      - Pitch_rate_6D
      - IMU_LongAccelVal
    args:
      act_name: relu
      lstm_hidden: 64
      lstm_layers: 2
      dropout_rates: [0.3, 0.3]
      hidden_dims: [64, 32]
      use_batchnorm: true
    trainer:
      epochs: 200

online_mlp:
  base:
    <<: *_base
    test_size: 0.1
    features:
      - IMU_VerAccelVal
      - Bounce_rate_6D
      - Pitch_rate_6D
      - IMU_LongAccelVal
    args:
      act_name: relu
      dropout_rates: [0.3, 0.3, 0.3]
      hidden_dims: [64, 64, 32]
      use_batchnorm: true
    trainer:
      learning_rate: 0.0005

linear_quad:
  base:
    <<: *_base
    features:
      - IMU_VerAccelVal
      - Bounce_rate_6D
      - Pitch_rate_6D
      - IMU_LongAccelVal
    args:
      C: 1.0
      form: linear_quad
      max_iter: 1000
      random_state: 0
      solver: lbfgs
    trainer: {}

quad_only:
  base:
    <<: *_base
    features:
      - IMU_VerAccelVal
      - Bounce_rate_6D
      - Pitch_rate_6D
      - IMU_LongAccelVal
    args:
      C: 1.0
      form: quad_only
      max_iter: 1000
      random_state: 0
      solver: lbfgs

quad_exp:
  base:
    <<: *_base
    features:
      - IMU_VerAccelVal
      - Bounce_rate_6D
      - Pitch_rate_6D
      - IMU_LongAccelVal
    args:
      C: 0.06576916117983621
      form: quad_exp
      max_iter: 1000
      random_state: 0
      solver: lbfgs
      w3: [1.0, 1.0, 1.0, 1.0]
      w4: [0.0, 0.0, 0.0, 0.0]
    trainer: {}