_base_nn:
  test_size: 0.2
  trainer: &id001
    batch_size: 128
    epochs: 200
    lam_smooth: 0.0
    learning_rate: 0.001
    weight_decay: 0.0
_base_reg:
  test_size: 0.2
  trainer: &id002 {}
강신길:
  offline_lstm:
    args:
      act_name: relu
      bidirectional: true
      dropout_rate: 0.3
      hidden_dims:
      - 64
      - 32
      lstm_hidden_dim: 64
      lstm_layers: 2
      use_batchnorm: true
    model_type: offline_lstm
    test_size: 0.2
    trainer: *id001
  online_combi_linear_quad:
    args:
      C: 1.0
      form: linear_quad
      max_iter: 1000
      random_state: 0
      solver: lbfgs
    model_type: online_combination
    test_size: 0.2
    trainer: *id002
  online_combi_quad_exp:
    args:
      C: 0.1
      form: quad_exp
      max_iter: 1000
      random_state: 0
      solver: lbfgs
      w3:
      - 0.2569583242334344
      - 0.30843756914754283
      - 7.148436557473784
      - 0.1448926139480688
      w4:
      - 1.2122182892289148
      - 4.774783995385079
      - 2.6413576527694467
      - 2.199800917390771
    model_type: online_combination
    test_size: 0.2
    trainer: *id002
  online_combi_quad_only:
    args:
      C: 0.02698177
      form: quad_only
      max_iter: 1000
      random_state: 0
      solver: lbfgs
    model_type: online_combination
    test_size: 0.2
    trainer: *id002
  online_combi_quad_only_bo_fs:
    args:
      C: 0.03852378615162033
      form: quad_only
      max_iter: 1000
      random_state: 0
      solver: lbfgs
    features:
      selected_indices:
      - 1
      - 
      use_feature_selection: true
    model_type: online_combination
    test_size: 0.2
    trainer: {}
  online_lstm:
    args:
      act_name: relu
      dropout_rates:
      - 0.3
      - 0.3
      hidden_dims:
      - 64
      - 32
      lstm_dropout: 0.3
      lstm_hidden_dim: 64
      lstm_layers: 2
      use_batchnorm: true
    model_type: online_lstm
    test_size: 0.2
    trainer: *id001
  online_lstm_bo:
    args:
      act_name: gelu
      dropout_rates:
      - 0.10422796743976102
      - 0.10422796743976102
      - 0.10422796743976102
      hidden_dims:
      - 64
      - 128
      - 128
      lstm_dropout: 0.39356319026532166
      lstm_hidden_dim: 64
      lstm_layers: 1
      use_batchnorm: false
    features:
      selected_indices: null
      use_feature_selection: false
    model_type: online_lstm
    test_size: 0.2
    trainer:
      batch_size: 32
      epochs: 200
      lam_smooth: 0.0
      learning_rate: 0.006117508335162371
      weight_decay: 0.00312905967633997
  online_mlp:
    args:
      act_name: relu
      dropout_rates:
      - 0.3
      - 0.3
      - 0.3
      hidden_dims:
      - 64
      - 64
      - 32
      use_batchnorm: true
    model_type: online_mlp
    test_size: 0.2
    trainer:
      batch_size: 128
      epochs: 200
      lam_smooth: 0.0
      learning_rate: 0.001
      weight_decay: 0.0
  online_mlp_bo_fs:
    args:
      act_name: gelu
      dropout_rates:
      - 0.037169589291268415
      - 0.037169589291268415
      - 0.037169589291268415
      - 0.037169589291268415
      - 0.037169589291268415
      - 0.037169589291268415
      hidden_dims:
      - 256
      - 64
      - 256
      - 32
      - 256
      - 256
      use_batchnorm: true
    features:
      selected_indices:
      - 0
      - 1
      - 2
      - 3
      use_feature_selection: true
    model_type: online_mlp
    test_size: 0.2
    trainer:
      batch_size: 128
      epochs: 200
      lam_smooth: 0.0
      learning_rate: 0.001
      weight_decay: 0.001720389310541731
박재일:
  offline_lstm:
    args:
      act_name: relu
      lstm_hidden: 64
      lstm_layers: 2
      dropout_rates:
      - 0.3
      - 0.3
      hidden_dims:
      - 64
      - 32
      use_batchnorm: true
    model_type: offline_lstm
    test_size: 0.2
    trainer: *id001
  online_combi_linear_quad:
    args:
      C: 1.0
      form: linear_quad
      max_iter: 1000
      random_state: 0
      solver: lbfgs
    model_type: online_combination
    test_size: 0.2
    trainer: *id002
  online_combi_quad_exp:
    args:
      C: 1.0
      form: quad_exp
      max_iter: 1000
      random_state: 0
      solver: lbfgs
      w3:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      w4:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    model_type: online_combination
    test_size: 0.2
    trainer: *id002
  online_combi_quad_only:
    args:
      C: 1.0
      form: quad_only
      max_iter: 1000
      random_state: 0
      solver: lbfgs
    model_type: online_combination
    test_size: 0.2
    trainer: *id002
  online_mlp:
    args:
      act_name: relu
      dropout_rates:
      - 0.3
      - 0.3
      - 0.3
      hidden_dims:
      - 64
      - 64
      - 32
      use_batchnorm: true
    model_type: online_mlp
    test_size: 0.2
    trainer:
      batch_size: 128
      epochs: 100
      lam_smooth: 0.0
      learning_rate: 0.0005
      weight_decay: 0.0
한규택:
  offline_lstm:
    args:
      act_name: relu
      lstm_hidden: 64
      lstm_layers: 2
      mlp_dropout: 0.3
      mlp_hiddens:
      - 64
      - 32
      use_batchnorm: true
    model_type: offline_lstm
    test_size: 0.2
    trainer: *id001
  online_combi_linear_quad:
    args:
      C: 1.0
      form: linear_quad
      max_iter: 1000
      random_state: 0
      solver: lbfgs
    model_type: online_combination
    test_size: 0.2
    trainer: *id002
  online_combi_quad_exp:
    args:
      C: 0.06576916117983621
      form: quad_exp
      max_iter: 1000
      random_state: 0
      solver: lbfgs
      w3:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      w4:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    model_type: online_combination
    test_size: 0.2
    trainer: *id002
  online_combi_quad_only:
    args:
      C: 1.0
      form: quad_only
      max_iter: 1000
      random_state: 0
      solver: lbfgs
    model_type: online_combination
    test_size: 0.2
    trainer: *id002
  online_mlp:
    args:
      act_name: relu
      dropout_rate: 0.3
      hidden_dims:
      - 64
      - 64
      - 32
      use_batchnorm: true
    model_type: online_mlp
    test_size: 0.2
    trainer:
      batch_size: 128
      epochs: 100
      lam_smooth: 0.0
      learning_rate: 0.0005
      weight_decay: 0.0
