_base: &_base
  test_size: 0.2
  trainer:
    lam_smooth: 0.0
    batch_size: 128
    learning_rate: 0.0005
    weight_decay: 0.0
    epochs: 100

강신길:
  online_mlp:
    model_type: online_mlp
    feature_version: v1
    args:
      hidden_dims: [64, 64, 32]
      dropout_rate: 0.3
      act_name: relu
      use_batchnorm: true
    test_size: 0.2
    trainer:
      lam_smooth: 0.0
      batch_size: 128
      learning_rate: 0.0005
      weight_decay: 0.0
      epochs: 100

  online_combination:
    <<: *_base
    model_type: online_combination
    feature_version: v1
    args:
      combi_type: quad_only
      max_iter: 1000
      C: 1.0
      solver: "lbfgs"
      random_state: 0

  offline_lstm:
    <<: *_base
    model_type: offline_lstm
    feature_version: v1
    args:
      lstm_hidden: 64
      lstm_layers: 2
      mlp_hiddens: [64, 32]
      mlp_dropout: 0.3
      act_name: relu
      use_batchnorm: true