_base_nn: &_base_nn
  test_size: 0.2
  trainer:
    lam_smooth: 0.0
    batch_size: 128
    learning_rate: 0.001
    weight_decay: 0.0
    epochs: 200

_base_reg: &_base_reg
  test_size: 0.2
  trainer: {}

강신길:
  online_mlp:
    model_type: online_mlp
    args:
      hidden_dims: [64, 64, 32]
      dropout_rate: 0.3
      act_name: relu
      use_batchnorm: true
    test_size: 0.2
    trainer:
      lam_smooth: 0.0
      batch_size: 128
      learning_rate: 0.001
      weight_decay: 0.0
      epochs: 200
  online_combi_quad_only:
    <<: *_base_reg
    model_type: online_combination
    args:
      form: quad_only
      max_iter: 1000
      C: 0.02698177
      solver: "lbfgs"
      random_state: 0

  online_combi_linear_quad:
    <<: *_base_reg
    model_type: online_combination
    args:
      form: linear_quad
      max_iter: 1000
      C: 1.0
      solver: "lbfgs"
      random_state: 0

  online_combi_quad_exp:
    <<: *_base_reg
    model_type: online_combination
    args:
      form: quad_exp
      max_iter: 1000
      C: 0.1
      solver: "lbfgs"
      random_state: 0
      w3: [0.2569583242334344, 0.30843756914754283, 7.148436557473784, 0.1448926139480688]
      w4: [1.2122182892289148, 4.774783995385079, 2.6413576527694467, 2.199800917390771]

  offline_lstm:
    <<: *_base_nn
    model_type: offline_lstm
    args:
      lstm_hidden: 64
      lstm_layers: 2
      mlp_hiddens: [64, 32]
      mlp_dropout: 0.3
      act_name: relu
      use_batchnorm: true

박재일:
  online_mlp:
    model_type: online_mlp
    args:
      hidden_dims: [64, 64, 32]
      dropout_rate: 0.3
      act_name: relu
      use_batchnorm: true
    test_size: 0.2
    trainer:
      lam_smooth: 0.0
      batch_size: 128
      learning_rate: 0.0005
      weight_decay: 0.0
      epochs: 100

  online_combi_quad_only:
    <<: *_base_reg
    model_type: online_combination
    args:
      form: quad_only
      max_iter: 1000
      C: 1.0
      solver: "lbfgs"
      random_state: 0

  online_combi_linear_quad:
    <<: *_base_reg
    model_type: online_combination
    args:
      form: linear_quad
      max_iter: 1000
      C: 1.0
      solver: "lbfgs"
      random_state: 0

  online_combi_quad_exp:
    <<: *_base_reg
    model_type: online_combination
    args:
      form: quad_exp
      max_iter: 1000
      C: 1.0
      solver: "lbfgs"
      random_state: 0
      w3: [1.0, 1.0, 1.0, 1.0]
      w4: [0.0, 0.0, 0.0, 0.0]

  offline_lstm:
    <<: *_base_nn
    model_type: offline_lstm
    args:
      lstm_hidden: 64
      lstm_layers: 2
      mlp_hiddens: [64, 32]
      mlp_dropout: 0.3
      act_name: relu
      use_batchnorm: true

한규택:
  online_mlp:
    model_type: online_mlp
    args:
      hidden_dims: [64, 64, 32]
      dropout_rate: 0.3
      act_name: relu
      use_batchnorm: true
    test_size: 0.2
    trainer:
      lam_smooth: 0.0
      batch_size: 128
      learning_rate: 0.0005
      weight_decay: 0.0
      epochs: 100

  online_combi_quad_only:
    <<: *_base_reg
    model_type: online_combination
    args:
      form: quad_only
      max_iter: 1000
      C: 1.0
      solver: "lbfgs"
      random_state: 0

  online_combi_linear_quad:
    <<: *_base_reg
    model_type: online_combination
    args:
      form: linear_quad
      max_iter: 1000
      C: 1.0
      solver: "lbfgs"
      random_state: 0

  online_combi_quad_exp:
    <<: *_base_reg
    model_type: online_combination
    args:
      form: quad_exp
      max_iter: 1000
      C:  0.06576916117983621
      solver: "lbfgs"
      random_state: 0
      w3: [1.0, 1.0, 1.0, 1.0]
      w4: [0.0, 0.0, 0.0, 0.0]

  offline_lstm:
    <<: *_base_nn
    model_type: offline_lstm
    args:
      lstm_hidden: 64
      lstm_layers: 2
      mlp_hiddens: [64, 32]
      mlp_dropout: 0.3
      act_name: relu
      use_batchnorm: true